# Generated by Django 3.2.3 on 2021-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descripcion',
            field=models.CharField(default='hola', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='hola', max_length=255),
        ),
    ]
