# Generated by Django 3.2.3 on 2021-06-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210614_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
